<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="9" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke Test" duration-ms="96456" started-at="2017-10-30T16:18:56Z" finished-at="2017-10-30T16:20:33Z">
    <groups>
    </groups>
    <test name="Login" duration-ms="49312" started-at="2017-10-30T16:18:56Z" finished-at="2017-10-30T16:19:45Z">
      <class name="Maven.automation_project.Smoke.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="setup" is-config="true" duration-ms="28622" started-at="2017-10-30T21:48:56Z" finished-at="2017-10-30T21:49:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Verify_User_is_Able_to_Login_With_Valid_Credentials()[pri:0, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_Able_to_Login_With_Valid_Credentials" duration-ms="9143" started-at="2017-10-30T21:49:25Z" finished-at="2017-10-30T21:49:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_Able_to_Login_With_Valid_Credentials -->
        <test-method status="PASS" signature="Verify_User_is_not_Able_to_Login_With_Blank_Credentials()[pri:1, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Blank_Credentials" duration-ms="1470" started-at="2017-10-30T21:49:34Z" finished-at="2017-10-30T21:49:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Blank_Credentials -->
        <test-method status="PASS" signature="Verify_User_is_not_Able_to_Login_With_Blank_Password()[pri:2, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Blank_Password" duration-ms="1471" started-at="2017-10-30T21:49:36Z" finished-at="2017-10-30T21:49:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Blank_Password -->
        <test-method status="PASS" signature="Verify_User_is_not_Able_to_Login_With_Invalid_EmailAddress()[pri:3, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Invalid_EmailAddress" duration-ms="1581" started-at="2017-10-30T21:49:37Z" finished-at="2017-10-30T21:49:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_EmailAddress -->
        <test-method status="SKIP" signature="Verify_User_is_not_Able_to_Login_With_Invalid_Password()[pri:4, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" duration-ms="2013" started-at="2017-10-30T21:49:39Z" finished-at="2017-10-30T21:49:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invali password.] but found [Invalid password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invali password.] but found [Invalid password.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Maven.automation_project.Pages.LoginPage.login_invalid_pass(LoginPage.java:106)
	at Maven.automation_project.Smoke.LoginTest.Verify_User_is_not_Able_to_Login_With_Invalid_Password(LoginTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
        <test-method status="SKIP" signature="Verify_User_is_not_Able_to_Login_With_Invalid_Password()[pri:4, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" duration-ms="2133" started-at="2017-10-30T21:49:41Z" finished-at="2017-10-30T21:49:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invali password.] but found [Invalid password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invali password.] but found [Invalid password.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Maven.automation_project.Pages.LoginPage.login_invalid_pass(LoginPage.java:106)
	at Maven.automation_project.Smoke.LoginTest.Verify_User_is_not_Able_to_Login_With_Invalid_Password(LoginTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1022)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1223)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
        <test-method status="FAIL" signature="Verify_User_is_not_Able_to_Login_With_Invalid_Password()[pri:4, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" duration-ms="1932" started-at="2017-10-30T21:49:43Z" finished-at="2017-10-30T21:49:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invali password.] but found [Invalid password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invali password.] but found [Invalid password.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Maven.automation_project.Pages.LoginPage.login_invalid_pass(LoginPage.java:106)
	at Maven.automation_project.Smoke.LoginTest.Verify_User_is_not_Able_to_Login_With_Invalid_Password(LoginTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1022)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1223)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
        <test-method status="PASS" signature="close_browser()[pri:0, instance:Maven.automation_project.Smoke.LoginTest@79e18e38]" name="close_browser" is-config="true" duration-ms="696" started-at="2017-10-30T21:49:45Z" finished-at="2017-10-30T21:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
      </class> <!-- Maven.automation_project.Smoke.LoginTest -->
    </test> <!-- Login -->
    <test name="Registration Test" duration-ms="47078" started-at="2017-10-30T16:19:46Z" finished-at="2017-10-30T16:20:33Z">
      <class name="Maven.automation_project.Smoke.RegistrationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:Maven.automation_project.Smoke.RegistrationTest@1d9bec4d]" name="setup" is-config="true" duration-ms="30602" started-at="2017-10-30T21:49:46Z" finished-at="2017-10-30T21:50:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Verify_User_is_able_Register_as_New_User()[pri:0, instance:Maven.automation_project.Smoke.RegistrationTest@1d9bec4d]" name="Verify_User_is_able_Register_as_New_User" duration-ms="12617" started-at="2017-10-30T21:50:16Z" finished-at="2017-10-30T21:50:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_able_Register_as_New_User -->
        <test-method status="PASS" signature="Verify_User_is_not_able_to_Register_with_Already_Regitered_Email()[pri:1, instance:Maven.automation_project.Smoke.RegistrationTest@1d9bec4d]" name="Verify_User_is_not_able_to_Register_with_Already_Regitered_Email" duration-ms="3160" started-at="2017-10-30T21:50:29Z" finished-at="2017-10-30T21:50:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_User_is_not_able_to_Register_with_Already_Regitered_Email -->
        <test-method status="PASS" signature="close_browser()[pri:0, instance:Maven.automation_project.Smoke.RegistrationTest@1d9bec4d]" name="close_browser" is-config="true" duration-ms="691" started-at="2017-10-30T21:50:32Z" finished-at="2017-10-30T21:50:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_browser -->
      </class> <!-- Maven.automation_project.Smoke.RegistrationTest -->
    </test> <!-- Registration Test -->
  </suite> <!-- Smoke Test -->
</testng-results>
